"""Core logic prototypes for Fractal Maze Lab."""

from .logic_core import (
    Address,
    AddressGraph,
    BlockAddress,
    BlockMoveGenerator,
    CantorHopRule,
    Connection,
    ExecutionError,
    ProofEdge,
    ProofRule,
    ProofPathStep,
    RuntimeState,
    StepRecord,
)
from .fractal_block import (
    KOTEITAN_DEFAULT_PATTERN,
    FractalBlockMaze,
    FractalBlockPattern,
    FractalBlockSearchResult,
)
from .port_graph import Port, PortGraph, PortTransition, PortTransitionGroup
from .solver import (
    BreadthFirstSolver,
    ExecutionStrategyRegistry,
    SolverResult,
    SolveStatus,
    default_strategy_registry,
    solve_address_graph_bfs,
    solve_fractal_block_bounded,
    solve_with_proof_rule,
)
from .tiled_port_graph import Terminal, TiledPortEdge, TiledPortGraph, TiledState
from .package_loader import (
    LoadedPackage,
    SolutionReplay,
    load_package,
    load_port_graph_logic,
    load_referenced_solution,
    load_solution,
    replay_solution,
)
from .package_validation import PackageValidationResult, ValidationIssue, validate_package_file
from .graph_layout import AutoGraphLayout, LAYOUT_ALGORITHM, LaidPoint, layout_port_graph
from .browser_export import (
    BROWSER_FORMAT,
    BrowserPackageExport,
    ExportError,
    build_catalogue_index,
    discover_packages,
    export_browser_package,
    write_browser_package,
    write_catalogue_index,
)

__all__ = [
    "Address",
    "AddressGraph",
    "BlockAddress",
    "BlockMoveGenerator",
    "CantorHopRule",
    "Connection",
    "ExecutionError",
    "ProofEdge",
    "ProofRule",
    "ProofPathStep",
    "RuntimeState",
    "StepRecord",
    "KOTEITAN_DEFAULT_PATTERN",
    "FractalBlockMaze",
    "FractalBlockPattern",
    "FractalBlockSearchResult",
    "Port",
    "PortGraph",
    "PortTransition",
    "PortTransitionGroup",
    "BreadthFirstSolver",
    "ExecutionStrategyRegistry",
    "SolverResult",
    "SolveStatus",
    "default_strategy_registry",
    "solve_address_graph_bfs",
    "solve_fractal_block_bounded",
    "solve_with_proof_rule",
    "Terminal",
    "TiledPortEdge",
    "TiledPortGraph",
    "TiledState",
    "LoadedPackage",
    "SolutionReplay",
    "load_package",
    "load_port_graph_logic",
    "load_referenced_solution",
    "load_solution",
    "replay_solution",
    "PackageValidationResult",
    "ValidationIssue",
    "validate_package_file",
    "AutoGraphLayout",
    "LAYOUT_ALGORITHM",
    "LaidPoint",
    "layout_port_graph",
    "BROWSER_FORMAT",
    "BrowserPackageExport",
    "ExportError",
    "build_catalogue_index",
    "discover_packages",
    "export_browser_package",
    "write_browser_package",
    "write_catalogue_index",
]
